import { test, expect, type Page } from '@playwright/test';

/**
 * FE-to-BE E2E: tanggal transaksi is backend-owned.
 *
 * The Pencatatan Transfer form used to carry a manual "Tanggal Transaksi" date
 * picker. It is gone: the backend stores NULL on create and stamps both
 * `transaction_date` and `requested_transfer_at` with server time only when the
 * transfer is APPROVED (FinanceManager decision), so the FE never sends — and
 * never generates — a date. This spec asserts that from the outside: no input
 * on the form, no key in the create/update payloads, "—" while DRAFT, still "—"
 * after submit, and a real date once approved.
 *
 * Requires FE + BE running locally — see e2e/README.md.
 */

const API_BASE_URL = process.env.E2E_API_BASE_URL || 'http://localhost:4000/api';

const SYSADMIN_EMAIL = process.env.E2E_SYSADMIN_EMAIL || 'sysadmin@kesh.local';
const SYSADMIN_PASSWORD = process.env.E2E_SYSADMIN_PASSWORD || 'SystemAdmin@123';

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

async function apiToken(): Promise<string> {
  const loginRes = await fetch(`${API_BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: SYSADMIN_EMAIL, password: SYSADMIN_PASSWORD }),
  });
  if (!loginRes.ok) throw new Error(`setup: login failed: ${loginRes.status}`);
  return (await loginRes.json()).access_token;
}

/**
 * Setup only — final FinanceManager approval, the event that stamps both
 * system dates. SystemAdmin has full access and may decide straight from
 * SUBMITTED, so the intermediate review layers are not needed here.
 */
async function approveOverApi(transferId: string) {
  const token = await apiToken();
  const res = await fetch(`${API_BASE_URL}/transfers/${transferId}/decision`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: JSON.stringify({ decision: 'APPROVE' }),
  });
  if (!res.ok) throw new Error(`setup: approval failed: ${res.status} ${await res.text()}`);
  return res.json();
}

/** Setup only — picks an existing APPROVED sender, never the workflow under test. */
async function resolveApprovedSender(): Promise<string> {
  const token = await apiToken();

  const res = await fetch(`${API_BASE_URL}/applications?status=APPROVED&limit=25`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  const body = await res.json();
  const apps: Array<{ display_name?: string }> = body.data ?? (Array.isArray(body) ? body : []);
  const found = apps.find((a) => a.display_name);
  if (!found) throw new Error('setup: no APPROVED application with a display_name exists locally.');
  return found.display_name!;
}

async function login(page: Page) {
  await page.goto('/login');
  await page.getByLabel('Email').fill(SYSADMIN_EMAIL);
  await page.getByLabel('Password').fill(SYSADMIN_PASSWORD);
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.waitForURL('**/dashboard');
}

function summaryCard(page: Page) {
  return page.locator('div.rounded-2xl').filter({ has: page.getByRole('heading', { name: 'Ringkasan' }) });
}

/** Value cell of a Ringkasan field, by its label. */
function summaryField(page: Page, label: string) {
  return summaryCard(page)
    .locator(`div:has(> div.text-xs:text-is("${label}")) > div.text-sm`)
    .first();
}

test.describe.configure({ mode: 'serial' });

test.describe('Tanggal transaksi is generated by the backend', () => {
  let senderName: string;
  let ts: string;
  let transferId: string;

  test.beforeAll(async () => {
    ts = Date.now().toString();
    senderName = await resolveApprovedSender();
  });

  test('create form has no date input and posts no transaction_date', async ({ page }) => {
    await login(page);
    await page.goto('/transfers/new');

    // 1. No manual date field — including inside the collapsed metadata panel,
    //    which is where it used to live.
    await page.getByRole('button', { name: /Metadata SNAP \/ Transfer/ }).click();
    await expect(page.getByText('Kanal Transfer')).toBeVisible(); // panel is open
    // `exact` matters: it also makes the match case-sensitive, so the helper
    // text below ("Tanggal transaksi akan…") does not count as the old label.
    await expect(page.getByText('Tanggal Transaksi', { exact: true })).toHaveCount(0);
    // The only date picker left is "Tanggal Eksekusi Diminta"
    // (requested_execution_date) — a SNAP field the user really does choose.
    // "Tanggal Diminta" (requested_transfer_at) is backend-generated too, so it
    // has no input either.
    await expect(page.locator('input[type="date"]')).toHaveCount(1);
    await expect(
      page.getByText('Tanggal transaksi akan dibuat otomatis saat transaksi diajukan.'),
    ).toBeVisible();

    await page.getByPlaceholder('Cari nama atau CIF pengirim…').fill(senderName);
    await page.getByRole('button', { name: new RegExp(escapeRegExp(senderName)) }).click();

    await page.locator('#transfer-amount').fill('1500000');
    await page.locator('#transfer-bank').selectOption({ index: 1 });
    await page.locator('#transfer-account-number').fill('9911005577');
    await page.locator('#transfer-account-name').fill(`E2E Penerima Tgl ${ts}`);
    await page.locator('#transfer-relationship').selectOption('Vendor');

    const createResponse = page.waitForResponse(
      (r) => /\/api\/transfers$/.test(new URL(r.url()).pathname) && r.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Buat Draft' }).click();
    const created = await createResponse;
    expect(created.ok(), await created.text().catch(() => '')).toBeTruthy();

    // 2. The payload carries no transaction_date at all — not even as null.
    const sent = created.request().postDataJSON();
    expect(Object.keys(sent), JSON.stringify(sent)).not.toContain('transaction_date');

    const body = await created.json();
    transferId = String(body.id);
    // Generated by the backend in the short format: TRF-XXXXXXXX, 12 chars.
    expect(body.partner_reference_no).toMatch(/^TRF-[A-HJ-NP-Z2-9]{8}$/);
    expect(String(body.partner_reference_no)).toHaveLength(12);
    // Backend stores NULL on create.
    expect(body.transaction_date ?? null).toBeNull();
  });

  test('draft shows — on the list and "-" on the detail, and editing sends no date', async ({ page }) => {
    await login(page);
    await page.goto(`/transfers/${transferId}`);

    // 4. DRAFT detail has the field, empty.
    await expect(summaryField(page, 'Tanggal Transaksi')).toHaveText('-');

    // 4. DRAFT list row shows the em dash.
    await page.goto('/transfers');
    const listRow = page.locator('div.border-t').filter({ hasText: `#${transferId}` }).first();
    await expect(listRow).toBeVisible();
    await expect(listRow.getByTestId('transfer-transaction-date')).toHaveText('Tgl. —');

    // 3. The edit form has no date field either, and PATCH sends no date.
    await page.goto(`/transfers/${transferId}`);
    await page.getByRole('button', { name: 'Ubah Transaksi' }).click();
    await expect(page.locator('#edit-amount')).toBeVisible();
    await expect(page.getByText('Tanggal Transaksi', { exact: true })).toHaveCount(1); // Ringkasan only

    await page.locator('#edit-amount').fill('1750000');
    const updateResponse = page.waitForResponse(
      (r) => new URL(r.url()).pathname.endsWith(`/transfers/${transferId}`) && r.request().method() === 'PATCH',
    );
    await page.getByRole('button', { name: 'Simpan Perubahan' }).click();
    const updated = await updateResponse;
    expect(updated.ok(), await updated.text().catch(() => '')).toBeTruthy();
    const patched = updated.request().postDataJSON();
    expect(Object.keys(patched), JSON.stringify(patched)).not.toContain('transaction_date');
    // Still NULL — editing a draft does not stamp a date.
    expect((await updated.json()).transaction_date ?? null).toBeNull();
  });

  test('submit does not stamp a date — it stays empty until approval', async ({ page }) => {
    await login(page);
    await page.goto(`/transfers/${transferId}`);

    const submitResponse = page.waitForResponse(
      (r) => new URL(r.url()).pathname.endsWith(`/transfers/${transferId}/submit`) && r.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Ajukan Transaksi' }).click();
    const submitted = await submitResponse;
    expect(submitted.ok(), await submitted.text().catch(() => '')).toBeTruthy();

    // 5. Submit is not an approval — the backend leaves both dates NULL.
    const body = await submitted.json();
    expect(body.status).toBe('SUBMITTED');
    expect(body.transaction_date ?? null, 'submit must NOT stamp a date').toBeNull();
    expect(body.requested_transfer_at ?? null).toBeNull();

    // Submit navigates to the list, which refetches — still the em dash.
    await page.waitForURL('**/transfers');
    const listRow = page.locator('div.border-t').filter({ hasText: `#${transferId}` }).first();
    await expect(listRow.getByTestId('transfer-transaction-date')).toHaveText('Tgl. —');

    await page.goto(`/transfers/${transferId}`);
    await expect(summaryField(page, 'Tanggal Transaksi')).toHaveText('-');
  });

  test('final approval stamps the date that detail and list then show', async ({ page }) => {
    // Setup only, not the workflow under test: drive the FinanceManager
    // approval over the API. SystemAdmin may decide straight from SUBMITTED,
    // so this needs no extra role credentials.
    const approved = await approveOverApi(transferId);
    const stamped = approved.transaction_date;
    expect(stamped, 'approval must stamp transaction_date').toBeTruthy();
    expect(approved.requested_transfer_at, 'approval must stamp requested_transfer_at').toBeTruthy();
    const expectedDate = new Date(stamped).toLocaleDateString('id-ID');

    await login(page);
    await page.goto('/transfers');
    const listRow = page.locator('div.border-t').filter({ hasText: `#${transferId}` }).first();
    await expect(listRow.getByTestId('transfer-transaction-date')).toHaveText(`Tgl. ${expectedDate}`);

    await page.goto(`/transfers/${transferId}`);
    const detailValue = summaryField(page, 'Tanggal Transaksi');
    await expect(detailValue).not.toHaveText('-');
    await expect(detailValue).toContainText(expectedDate);
  });
});
